AWSTemplateFormatVersion: '2010-09-09'
Description: Example CloudFormation template with security issues for testing

Parameters:
  DatabasePassword:
    Type: String
    Description: Database password (should use NoEcho!)

  ApiKey:
    Type: String
    Description: API key for external service

Resources:
  # S3 Bucket - Multiple security issues
  InsecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-insecure-bucket
      # Missing: BucketEncryption
      # Missing: PublicAccessBlockConfiguration
      # Missing: VersioningConfiguration
      # Missing: LoggingConfiguration

  # Security Group - Open to the world
  InsecureSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Insecure security group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # CRITICAL: SSH open to the world
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # CRITICAL: RDP open to the world
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
        # CRITICAL: Database port open to the world
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  # EC2 Instance - Multiple issues
  InsecureEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678
      InstanceType: t3.micro
      # Missing: IamInstanceProfile
      # Missing: Monitoring (detailed monitoring)
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true  # Public IP
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref InsecureSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            Encrypted: false  # Not encrypted!
      # Missing: MetadataOptions (IMDSv2)

  # RDS Instance - Multiple issues
  InsecureRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: insecure-db
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: 20
      PubliclyAccessible: true  # CRITICAL: Public!
      StorageEncrypted: false   # Not encrypted!
      # Missing: MultiAZ
      # Missing: BackupRetentionPeriod
      # Missing: DeletionProtection
      # Missing: EnableCloudwatchLogsExports
      AutoMinorVersionUpgrade: false  # Should be true

  # IAM Role - Overly permissive
  InsecureIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: InsecureRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'  # CRITICAL: Allows any AWS principal!
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AdminPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'      # CRITICAL: All actions!
                Resource: '*'    # CRITICAL: All resources!

  # Lambda Function - Multiple issues
  InsecureLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: insecure-function
      Runtime: python3.6  # Deprecated runtime!
      Handler: index.handler
      Code:
        ZipFile: |
          def handler(event, context):
              return 'Hello'
      Role: !GetAtt InsecureIAMRole.Arn
      Environment:
        Variables:
          DATABASE_PASSWORD: hardcoded-password-123  # Hardcoded secret!
          API_KEY: sk-12345678  # Hardcoded API key!
      # Missing: VpcConfig
      # Missing: TracingConfig
      # Missing: DeadLetterConfig
      # Missing: KmsKeyArn

  # API Gateway - No authorization
  InsecureApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: GET
      AuthorizationType: NONE  # No auth!
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InsecureLambdaFunction.Arn}/invocations

  # SQS Queue - Not encrypted
  InsecureSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: insecure-queue
      # Missing: KmsMasterKeyId
      # Missing: RedrivePolicy (DLQ)

  # SNS Topic - Not encrypted
  InsecureSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: insecure-topic
      # Missing: KmsMasterKeyId

  # ECS Task Definition - Security issues
  InsecureECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: insecure-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: insecure-container
          Image: my-image:latest
          Privileged: true  # CRITICAL: Privileged mode!
          # User: root  # Running as root (implicit)
          # Missing: ReadonlyRootFilesystem
          # Missing: LogConfiguration
          Environment:
            - Name: DB_PASSWORD
              Value: secret123  # Hardcoded password!

  # CloudTrail - Missing encryption and validation
  InsecureCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: insecure-trail
      S3BucketName: !Ref CloudTrailBucket
      IsLogging: true
      IsMultiRegionTrail: false  # Should be true
      EnableLogFileValidation: false  # Should be true
      # Missing: KMSKeyId
      # Missing: CloudWatchLogsLogGroupArn

  # VPC without Flow Logs
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      # No Flow Logs configured!

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: InsecureAPI
      # Missing: EndpointConfiguration
      # Missing: Policy (resource policy)

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: data

  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudtrail-logs-bucket

Outputs:
  BucketName:
    Value: !Ref InsecureS3Bucket
  InstanceId:
    Value: !Ref InsecureEC2Instance
